#' @importFrom graphics .filled.contour 
#' @importFrom graphics axis 
#' @importFrom graphics box
#' @importFrom graphics contour 
#' @importFrom graphics image 
#' @importFrom graphics layout
#' @importFrom graphics lcm
#' @importFrom graphics par 
#' @importFrom graphics plot
#' @importFrom graphics plot.new 
#' @importFrom graphics plot.window 
#' @importFrom graphics points
#' @importFrom graphics polygon
#' @importFrom graphics rect
#' @importFrom graphics text
#' @importFrom graphics title
#' @importFrom grDevices hsv
#' @importFrom grDevices rainbow
#' @importFrom grDevices rgb
#' @importFrom stats runif
NULL
